Traceback (most recent call last):
  File "/home/jovyan/typethon/src/pyyc/compile.py", line 133, in <module>
    main()
  File "/home/jovyan/typethon/src/pyyc/compile.py", line 123, in main
    asm = compile(sys.argv[1])
  File "/home/jovyan/typethon/src/pyyc/compile.py", line 35, in compile
    TypeCheck().visit(tree)
  File "/opt/conda/lib/python3.10/ast.py", line 412, in visit
    return visitor(node)
  File "/opt/conda/lib/python3.10/ast.py", line 420, in generic_visit
    self.visit(item)
  File "/opt/conda/lib/python3.10/ast.py", line 412, in visit
    return visitor(node)
  File "/opt/conda/lib/python3.10/ast.py", line 422, in generic_visit
    self.visit(value)
  File "/opt/conda/lib/python3.10/ast.py", line 412, in visit
    return visitor(node)
  File "/home/jovyan/typethon/src/pyyc/type_checking/type_check.py", line 149, in visit_Call
    self.visit(node.args[0])
  File "/opt/conda/lib/python3.10/ast.py", line 412, in visit
    return visitor(node)
  File "/home/jovyan/typethon/src/pyyc/type_checking/type_check.py", line 88, in visit_BinOp
    node.type = InferenceRules.BinAdd(node.left.type, node.right.type)
AttributeError: 'Call' object has no attribute 'type'
